"""Models and store protocol for named estimate snapshots.

A ``SavedEstimate`` is an immutable snapshot of a completed session that the
user has chosen to persist under a human-readable label.  Each snapshot is
owned by an anonymous ``user_id`` — an opaque UUID generated by the browser
and sent on every request as ``X-Gauge-User-Id``.  Ownership is enforced by
``rename`` and ``delete``: callers that supply a ``user_id`` that does not
match the snapshot's owner receive a ``PermissionError``.

The ``SavedEstimateStore`` protocol defines the four CRUD operations; both
``InMemorySavedEstimateStore`` (for tests and ``GAUGE_NO_PERSIST=1``) and
``SqliteSavedEstimateStore`` (the production default) satisfy it.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Protocol

from pydantic import BaseModel, ConfigDict, Field

from gauge.benefits.models import Plan
from gauge.predictor.annual_cost import OopInterval
from gauge.predictor.model import CostPrediction
from gauge.predictor.schemas import PredictionFeatures


class SavedEstimate(BaseModel):
    """An immutable named snapshot of a completed estimation session.

    Parameters
    ----------
    id : str
        Unique identifier assigned at save time.
    user_id : str
        Anonymous identity of the owning browser session.  Opaque UUID
        generated by the frontend and sent as ``X-Gauge-User-Id``.
    label : str
        Human-readable name chosen by the user (e.g. ``"Blue Shield Gold 2025"``).
    features : PredictionFeatures
        Demographic inputs used for the prediction.
    prediction : CostPrediction
        Raw ML prediction (median, mean, conformal interval) in cents.
    plan : Plan or None
        The confirmed plan at time of saving, or ``None`` if no plan was set.
    oop_interval : OopInterval or None
        Conformal OOP interval, or ``None`` if no plan was confirmed.
    created_at : datetime
        UTC timestamp of when the estimate was saved.
    """

    model_config = ConfigDict(frozen=True)

    id: str
    user_id: str
    label: str
    features: PredictionFeatures
    prediction: CostPrediction
    plan: Plan | None = None
    oop_interval: OopInterval | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class SavedEstimateStore(Protocol):
    """Protocol for saved-estimate persistence backends.

    Both ``InMemorySavedEstimateStore`` and ``SqliteSavedEstimateStore``
    satisfy this protocol.  Use the protocol type in signatures rather than
    the concrete implementations so the backing store can be swapped in tests.
    """

    def save(
        self,
        user_id: str,
        label: str,
        features: PredictionFeatures,
        prediction: CostPrediction,
        plan: Plan | None,
        oop_interval: OopInterval | None,
    ) -> SavedEstimate:
        """Persist a new named estimate snapshot owned by ``user_id``.

        Parameters
        ----------
        user_id : str
            Anonymous identity of the requesting user.
        label : str
            User-supplied name for this snapshot.
        features : PredictionFeatures
            Demographics used for the prediction.
        prediction : CostPrediction
            Raw ML prediction.
        plan : Plan or None
            Confirmed plan, or ``None``.
        oop_interval : OopInterval or None
            OOP interval, or ``None``.

        Returns
        -------
        SavedEstimate
            The newly created snapshot with an assigned ``id``.
        """
        ...

    def list(self, user_id: str) -> list[SavedEstimate]:
        """Return all estimates owned by ``user_id``, newest first.

        Parameters
        ----------
        user_id : str
            Caller's anonymous identity.

        Returns
        -------
        list[SavedEstimate]
            Snapshots owned by ``user_id``, sorted by ``created_at`` descending.
        """
        ...

    def get(self, estimate_id: str) -> SavedEstimate | None:
        """Retrieve a single saved estimate by ID regardless of owner.

        Used internally to verify ownership before mutating.

        Parameters
        ----------
        estimate_id : str
            The ``id`` of the snapshot to fetch.

        Returns
        -------
        SavedEstimate or None
            The snapshot, or ``None`` if not found.
        """
        ...

    def rename(self, estimate_id: str, user_id: str, label: str) -> SavedEstimate:
        """Update the label of an estimate the caller owns.

        Parameters
        ----------
        estimate_id : str
            The ``id`` of the snapshot to rename.
        user_id : str
            Caller's anonymous identity.  Must match the snapshot's owner.
        label : str
            New label to assign.

        Returns
        -------
        SavedEstimate
            Updated snapshot.

        Raises
        ------
        KeyError
            If no snapshot with ``estimate_id`` exists.
        PermissionError
            If ``user_id`` does not match the snapshot's owner.
        """
        ...

    def delete(self, estimate_id: str, user_id: str) -> None:
        """Remove an estimate the caller owns.

        Parameters
        ----------
        estimate_id : str
            The ``id`` of the snapshot to delete.
        user_id : str
            Caller's anonymous identity.  Must match the snapshot's owner.

        Raises
        ------
        KeyError
            If no snapshot with ``estimate_id`` exists.
        PermissionError
            If ``user_id`` does not match the snapshot's owner.
        """
        ...


class InMemorySavedEstimateStore:
    """Thread-unsafe in-memory implementation of ``SavedEstimateStore``.

    Suitable for development, tests, and ``GAUGE_NO_PERSIST=1``.
    State is lost on process restart.
    """

    def __init__(self) -> None:
        self._store: dict[str, SavedEstimate] = {}

    def save(
        self,
        user_id: str,
        label: str,
        features: PredictionFeatures,
        prediction: CostPrediction,
        plan: Plan | None,
        oop_interval: OopInterval | None,
    ) -> SavedEstimate:
        """Persist a new named estimate snapshot owned by ``user_id``."""
        estimate = SavedEstimate(
            id=uuid.uuid4().hex[:16],
            user_id=user_id,
            label=label,
            features=features,
            prediction=prediction,
            plan=plan,
            oop_interval=oop_interval,
        )
        self._store[estimate.id] = estimate
        return estimate

    def list(self, user_id: str) -> list[SavedEstimate]:
        """Return all estimates owned by ``user_id``, newest first."""
        return sorted(
            (e for e in self._store.values() if e.user_id == user_id),
            key=lambda e: e.created_at,
            reverse=True,
        )

    def get(self, estimate_id: str) -> SavedEstimate | None:
        """Retrieve a single saved estimate by ID regardless of owner."""
        return self._store.get(estimate_id)

    def rename(self, estimate_id: str, user_id: str, label: str) -> SavedEstimate:
        """Update the label of an estimate the caller owns."""
        existing = self._store.get(estimate_id)
        if existing is None:
            raise KeyError(estimate_id)
        if existing.user_id != user_id:
            raise PermissionError(estimate_id)
        updated = existing.model_copy(update={"label": label})
        self._store[estimate_id] = updated
        return updated

    def delete(self, estimate_id: str, user_id: str) -> None:
        """Remove an estimate the caller owns."""
        existing = self._store.get(estimate_id)
        if existing is None:
            raise KeyError(estimate_id)
        if existing.user_id != user_id:
            raise PermissionError(estimate_id)
        del self._store[estimate_id]
